# Use postgres/example user/password credentials
version: '3.4'

services:

  postgres:
    container_name: nails_instance
    image: postgres
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_DB: nails
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: borkata
    volumes:
    - ./postgresql/data:/var/lib/postgresql/data
