# Generated by Django 3.2.5 on 2021-07-07 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sonq_nails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('nail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonq_nails.nail')),
            ],
        ),
    ]
