# Generated by Django 3.2.5 on 2021-07-27 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sonq_nails', '0002_auto_20210727_0949'),
        ('common', '0002_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='nail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonq_nails.nails'),
        ),
    ]
