# Generated by Django 3.2.5 on 2021-07-28 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_comment_nail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='nail',
            new_name='nails',
        ),
    ]
