# Generated by Django 3.2.5 on 2021-07-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20210731_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.TimeField(verbose_name='%H:%M'),
        ),
    ]
