# Generated by Django 3.2.5 on 2021-07-27 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sonq_nails', '0002_auto_20210727_0949'),
        ('common', '0003_alter_comment_nail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nail',
        ),
    ]
