# Generated by Django 3.2.5 on 2021-07-28 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sonq_nails', '0003_delete_nail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='pet',
            new_name='nails',
        ),
    ]
