# Generated by Django 3.2.5 on 2021-08-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonq_nails', '0005_auto_20210801_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nails',
            name='type',
            field=models.CharField(choices=[('Pedicure', 'Pedicure'), ('Manicure', 'Manicure'), ('Else', 'Else')], default='Else', max_length=10),
        ),
    ]
