# Generated by Django 3.2.5 on 2021-08-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonq_nails', '0006_alter_nails_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nails',
            name='feedback',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], default='Positive', max_length=50),
        ),
        migrations.AlterField(
            model_name='nails',
            name='type',
            field=models.CharField(choices=[('Pedicure', 'Pedicure'), ('Manicure', 'Manicure')], default='Manicure', max_length=10),
        ),
    ]
