# Generated by Django 3.2.5 on 2021-08-09 19:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sonq_nails', '0008_alter_nails_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nails',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
