# Generated by Django 3.2.5 on 2021-08-09 20:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sonq_nails', '0009_alter_nails_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nails',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
